// Electron - Configuration and deploy
// Created by Daniel Plata
// Do not edit this file !

const {app, BrowserWindow } = require('electron'); 
const path = require('path');

const createWindow = () => {
    const win = new BrowserWindow({
        width: 1400,
        height: 900,
        fullScreenable: true
    })

    // win.loadFile("src/index.html")o
    win.loadURL(`http://localhost:4200/`);
    // win.fullScreenable(true);
    // win.setMenu(null);

    // win.webContents.openDevTools();


    // win.loadurl(
    //     url.format({
    //         pathname: path.join(__dirname, `/dist/angular-test/index.html`),
    //         protocol: "file:",
    //         slashes: true
    //     })
    // );
}

app.whenReady().then(() => {
    createWindow()
})

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') app.quit()
})